CREATE TABLE BOARD_TBL(
	IDX NUMBER(6) NOT NULL PRIMARY KEY,
	WRITER VARCHAR2(20),
	SUBJECT VARCHAR2(255),
	CONTENT CLOB,
	CONDATE TIMESTAMP
);

SELECT * FROM BOARD_TBL;

CREATE SEQUENCE BOARD_SEQ_IDX
INCREMENT BY 1
START WITH 1;

SELECT BOARD_SEQ_IDX.NEXTVAL FROM DUAL;

CREATE TABLE COMMENT_TBL(
	IDX NUMBER(6) NOT NULL PRIMARY KEY,
	BIDX NUMBER(6),
	WRITER VARCHAR2(20),
	CONTENT CLOB,
	COMDATE TIMESTAMP
);