SELECT IDX, WRITER, SUBJECT, CONTENT, CONDATE FROM BOARD_TBL;

SELECT IDX, WRITER, SUBJECT, CONTENT, CONDATE FROM BOARD_TBL WHERE IDX = 1;

INSERT INTO BOARD_TBL VALUES (?, ?, ?, ?, ?);

SELECT MAX(IDX)+1 FROM BOARD_TBL;

UPDATE BOARD_TBL SET WRITER = ?, SUBJECT = ?, CONTENT = ? WHERE IDX = ?;

DELETE FROM BOARD_TBL WHERE IDX = 11;

------------------
SELECT * FROM COMMENT_TBL;

SELECT IDX, BIDX, WRITER, CONTENT, COMDATE FROM COMMENT_TBL WHERE BIDX = 12;

SELECT MAX(IDX)+1 FROM COMMENT_TBL;

INSERT INTO COMMENT_TBL VALUES (?, ?, ?, ?, ?);

DELETE FROM COMMENT_TBL WHERE IDX = ?;